/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.trainrec.storage.csv;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
